services:
  june:
    container_name: june
    image: fawni/june
    restart: unless-stopped
    environment:
      JUNE_PORT: 6489
      JUNE_TOKEN: "meow"
    ports:
      - "6489"
    volumes:
      - junecdn:/home/menhera/.local/share/june

volumes:
  junecdn:
