services:
  june:
    build: .
    restart: unless-stopped
    environment:
      JUNE_PORT: 6489
      JUNE_TOKEN: ""
    ports:
      - "6489:6489"
    volumes:
      - junecdn:/home/menhera/.local/share/june
    networks:
      - june

volumes:
  junecdn:

networks:
  june:
