name: check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.5.1"
          rebar3-version: "3.24.0"
          elixir-version: "1.17.3"
      - run: gleam deps download
      - run: gleam check
      - run: gleam format --check src
