name: check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "29.1.1"
          gleam-version: "1.18.1"
          rebar3-version: "3.25.1"
          elixir-version: "1.20.4"
      - run: gleam deps download
      - run: gleam check
      - run: gleam format --check src
